sudo: required
sudo: false
language: minimal
addons:
  artifacts:
    debug: true

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck-alpine

script:
  - docker run -v "$(pwd)":/wd 'shellcheck /wd/jhalfs/jhalfs'
  - docker run -v "$(pwd)":/wd 'shellcheck /wd/jhalfs/common/*.sh'
